### ISSUE TITLE
フレーム検討

### ISSUE THREAD

**Issue by T0YO3** [ex-n-soldiers/sample-site#1]

**Comment by mongolyy** [comment]
一覧画面 (tableタグで作る)

* タイトル(aタグで囲まれている)
* 商品の価格

詳細画面

* タイトル
* 商品の価格
* 内容
* 商品の画像
* 商品説明のPDF

**Comment by T0YO3** [comment]
@mongolyy 
[サンプルサイト画面イメージ.xlsx](https://github.com/ex-n-soldiers/sample-site/files/4008979/default.xlsx)を作ってみました。こんな感じで良いかね？

**Comment by mongolyy** [comment]
いいと思う！

**Comment by T0YO3** [comment]
@mongolyy 
早速確認ありがとう！もう少し情報を[サンプルサイト画面イメージ.xlsx](https://github.com/ex-n-soldiers/sample-site/files/4008994/default.xlsx)に追記しました。
「企業タイトル募集」は別途相談かな。いいのあれば教えて！画像でもいいと思う。

**Comment by T0YO3** [comment]
企業タイトルの件は、Issue #3 にて起票済み。

**Comment by T0YO3** [comment]
フレームは決定したため、本Issueはクローズする
