### ISSUE TITLE
企業タイトル

### ISSUE THREAD

**Issue by T0YO3** [ex-n-soldiers/sample-site#3]
サンプル画面の上部に表示する企業タイトルを決定する。

文字でも画像でも良いと思う。

**Comment by mongolyy** [comment]
![ex-n-soldiers store-logo-black](https://user-images.githubusercontent.com/10972787/71568865-c9e4b680-2b0d-11ea-9c2d-e2d548c7c20b.png)

ちなみに[ここ](https://www.squarespace.com/logo#N4IghgrgLgFgpgExALigJwnAvkA)で作った
利用について、多分無料だが、規約を読んだが値段は結局よくわからんかった
（ちなみに、1年くらい前は商用利用のロゴでなければ無料だった）

**Comment by T0YO3** [comment]
@mongolyy 
かっこいい！！いいね:+1:
ただ、ライセンスは要確認だね。こちらでも見てみるよ。

**Comment by T0YO3** [comment]
![logo](https://user-images.githubusercontent.com/59299336/71571180-6f068b80-2b1c-11ea-969e-9bb6f5702932.png)
ライセンス調べたけど、よく分からなかったのと、なんとなく有料っぽいから、モンゴルから教えてもらった白黒シルエットのサイトのものを使って作ってみました。

**Comment by T0YO3** [comment]
企業タイトルはとりあえず決まったため、本Issueはクローズする
