### ISSUE TITLE
商品内容

### ISSUE THREAD

**Issue by T0YO3** [ex-n-soldiers/sample-site#4]
商品一覧画面で取り扱う商品を決める。

画像の著作権に影響するため、以下の基準を考慮する。
・自分で画像を用意できる商品
・フリー画像で用意できる商品
・上記を満たす商品5つ

**Comment by T0YO3** [comment]
@mongolyy 
商品一覧で取り扱う内容を決めてなかったから決めたいです。
画像の著作権を考慮すると自分たちで揃えられるものが一番手っ取り早いと思う。
自分で撮った写真を見てみると、食べ物の写真が多数出てきたからそれでもいい？？

**Comment by mongolyy** [comment]
> 自分で撮った写真を見てみると、食べ物の写真が多数出てきたからそれでもいい？？
それでもいいし

アイコン系であれば、
https://www.silhouette-illust.com/
とか、写真系であれば、https://unsplash.com/ とか商用利用OKで、良さげな画像が多いからおすすめ

**Comment by T0YO3** [comment]
@mongolyy 
ありがとう！
白黒アイコンの家電にしようと思う。値段の変動も起こりやすい商品だし。

**Comment by T0YO3** [comment]
企業ロゴが白黒なので、商品写真はカラーにするため、unsplashから以下のものを使うことにします。
・カメラ(camera)
・ヘッドフォン(headphone)
・スマホ(smartphone)
・腕時計(watch)
・PC(laptop)
